#!/usr/bin/env perl

use strict;
use Error qw(:try);
use Sys::Syslog;
use File::Basename;
use lib dirname($0)."/lib";
use GenInit::Core;

# Not the most reliable way to get the arguments but eh...
my $prog = $ARGV[0];
my $start_action = $ARGV[1];
my $stop_action;
if(!$ARGV[2]){$stop_action = "killproc \$prog";}else{$stop_action = $ARGV[2];}

try {
	my $geninit = GenInit::Core->new(
		prog => $prog,
		start_action => $start_action,
		stop_action => $stop_action,
	);
	$geninit->generate_init();
}

catch Error with {
	my $ex = shift;
	print "Error catched: $ex->{-text}\n";
	syslog("info", "$ex->{-text}");
    exit 1;
}
